kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend
  #we must give namespace name otherwise it will go by default
  namespace: expense
  #labels of deployment resource
  labels:
    app: backend
    tier: backend
    project: expense
    version: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      tier: backend
      project: expense
      version: blue
  ##pod template
  template:
    metadata:
      labels:
        app: backend
        tier: backend
        project: expense 
        version: blue
    spec:
      containers:
      - name: backend
      #manifesto file
        image: khalidaws2024/backend:1.0.0